# Generated by Django 6.1.1 on 2026-09-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs_limit', models.PositiveSmallIntegerField(default=6)),
                ('toss_decision', models.CharField(blank=True, choices=[('bat', 'Bat'), ('bowl', 'Bowl')], max_length=4)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='scoring.match')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scoring.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scoring.team')),
            ],
            options={
                'verbose_name_plural': 'innings',
                'ordering': ['match', 'number'],
                'unique_together': {('match', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveSmallIntegerField()),
                ('ball_in_over', models.PositiveSmallIntegerField()),
                ('runs_off_bat', models.PositiveSmallIntegerField(default=0)),
                ('extra_type', models.CharField(blank=True, choices=[('', 'None'), ('wd', 'Wide'), ('nb', 'No ball'), ('b', 'Bye'), ('lb', 'Leg bye')], default='', max_length=2)),
                ('extra_runs', models.PositiveSmallIntegerField(default=0)),
                ('wicket_type', models.CharField(blank=True, choices=[('', 'None'), ('bowled', 'Bowled'), ('caught', 'Caught'), ('lbw', 'LBW'), ('run_out', 'Run out'), ('stumped', 'Stumped'), ('hit_wicket', 'Hit wicket')], default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='scoring.innings')),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_faced', to='scoring.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_bowled', to='scoring.player')),
                ('dismissed_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissals', to='scoring.player')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scoring.player')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scoring.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='scoring.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='scoring.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tosses_won', to='scoring.team'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team')},
        ),
    ]
