# Generated by Django 6.1.1 on 2026-09-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innings',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scoring.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scoring.player'),
        ),
        migrations.AddField(
            model_name='innings',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scoring.player'),
        ),
    ]
