# Generated by Django 6.1.1 on 2026-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_innings_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('batter', 'Batter'), ('bowler', 'Bowler'), ('allrounder', 'All-rounder')], default='allrounder', max_length=10),
        ),
    ]
