# Generated by Django 6.1.1 on 2026-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_team_soft_delete'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_active_team_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
    ]
