# Generated by Django 6.1.2 on 2026-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_rules_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
